### ISSUE TITLE
Package for luarocks?

### ISSUE THREAD

**Issue by mrcjkb** [CWood-sdf/banana.nvim#1]
Hey 👋 

This looks like a great candidate for luarocks,
which recent plugin managers such as [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) or [lazy.nvim (v11+)](https://github.com/folke/lazy.nvim/releases/tag/v11.0.0) can leverage to auto-install dependencies.

See https://github.com/nvim-neorocks/rocks.nvim/wiki/Plugin-support for how to do this. If you are interested, let me know if you need any help 😀.

**Comment by CWood-sdf** [comment]
I think I have everything set up for luarocks. If you would like to check if everything is fine, that would be really helpful! The package should be put onto luarocks when I publish 0.1.0 which should happen when I get the display:grid renderer in a state that I am happy with

**Comment by mrcjkb** [comment]
Looks good to me. 🚀 

Just one thing: I would suggest to bump the luarocks-tag-release version to v7.
