### ISSUE TITLE
Bug: Buffer rename error when repeatedly creating banana instances

### ISSUE THREAD

**Issue by theKnightsOfRohan** [CWood-sdf/banana.nvim#6]
When using a simple launch file to create a new banana instance, it's common practice to source a simple jumpstart script multiple times in order to launch a banana instance. However, when doing this command multiple times, you get the following error:

```
E5108: Error executing lua: ...eth/Documents/GitHub/banana.nvim/lua/banana/instance.lua:481: Failed to rename buffer
stack traceback:
	[C]: in function 'nvim_buf_set_name'
	...eth/Documents/GitHub/banana.nvim/lua/banana/instance.lua:481: in function '_createWinAndBuf'
	...eth/Documents/GitHub/banana.nvim/lua/banana/instance.lua:585: in function '_render'
	...eth/Documents/GitHub/banana.nvim/lua/banana/instance.lua:221: in function 'open'
	[string ":source (no file)"]:4: in function <[string ":source (no file)"]:3>
```

The launch file is as written below:

```lua
local instance = require('banana').newInstance("stuff/clock", "random buffer name")

instance:open()
```

I would expect that banana be able to gracefully handle this error, or maybe format it in a way for the user to easily see what's going on.

Steps to reproduce:
1. Have a basic banana project consisting of solely the nml file in the `banana/` directory and this launch script.
2. Open the launch script and source it using `:so`
3. Verify that the nml file loads and opens as expected.
4. Quit out of the render using :q
5. Re-source the script and observe the error using `:messages`

**Comment by CWood-sdf** [comment]
Yeah that's a bit of a weird error and kinda annoying

I will probably add the following to prevent this:
- add a findInstance method that takes in buffer name or something to identify instances
- add a buf name overlap check

**Comment by CWood-sdf** [comment]
I just wrote a fix for this, I'm not quite sure if I like how I did it, but it technically fixes the issue. I might change the fix to something more explicit in the api, but for now I will close the issue.
